# create your Kivy layout in the kv language here
BoxLayout:
    BoxLayout:
        orientation: "vertical"
        size_hint: 0.5,0.5
        Button:
            text: "List Required"
        Button:
            text: "List Completed"
        Button:
            text: "Add New Book"
        Button:
            text: "Title"
        Button:
            text: "Author"
        Button:
            text: "Pages"



    BoxLayout:
        orientation: "vertical"
        id: entriesBox